#!/bin/bash
# DO NOT execute this file as super-user
# Script to install OpenCV-3.0.0 on ubuntu 14.04 64-bit PC after installing step1, step2, step3, and step4 scripts (Though it should work independently as well)

# Prerequisites:
# --> Install ubuntu-14.04 (64-bit) on a PC (preferably 4GB RAM) and sufficient free space
# --> Copy the Backup folder on the Desktop (It contains all main tar files for jdk, ant, maven, hipi etc)
#     If the path is changed then make necessary changes in the script as well
# --> Make sure you are connected to Internet.
 
# Step 5: OpenCV-3.0.0
# Extract OpenCV in ~/opencv or git clone to the new directory
mkdir -p /home/hadoop/opencv
unzip -d /home/hadoop/opencv/ /home/hadoop/Desktop/Backup/opencv-3.0.0.zip

# Install dependencies
sudo apt-get update
sudo apt-get install libopencv-dev build-essential checkinstall cmake pkg-config yasm libtiff4-dev libjpeg-dev libjasper-dev libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev libxine-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev libv4l-dev python-dev python-numpy libtbb-dev libqt4-dev libgtk2.0-dev libfaac-dev libmp3lame-dev libopencore-amrnb-dev libopencore-amrwb-dev libtheora-dev libvorbis-dev libxvidcore-dev x264 v4l-utils libav-tools

# Check that following info is displayed
# FFMPEG: YES
# GStreamer: YES
# V4L/V4L2: Using libv4l (ver ...)

# Building OpenCV
cd /home/hadoop/opencv/opencv-3.0.0
mkdir release
cd release
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON ..


# notification Build files have been written to ....opencv-3.0.0/release
make
sudo make install

# Configure system wide library search path
sudo /bin/bash -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
sudo ldconfig


# reboot manually

