#!/bin/bash
# Run this as super-user
# Script to install the following softwares on a fresh ubuntu 14.04 64-bit PC
# 1. Scala 2.11.7

# Prerequisites:
# --> Install ubuntu-14.04 (64-bit) on a PC (preferably 4GB RAM) and sufficient free space
# --> sudo apt-get update
# --> Run software updater and install the latest software updates
# --> Copy the Backup folder on the Desktop (It contains all main tar files for jdk, ant, maven, hipi etc)
#     If the path is changes then make necessary changes in the script as well
# --> setup JDK1.8 and hadoop
 
# Installing Scala 2.11.7
mkdir -p /usr/local/scala
tar -zxvf /home/hadoop/Desktop/Backup/scala-2.11.7.tgz -C /usr/local/scala


# Set the environment variables (append the following lines to ~/.bashrc )
# Update .bashrc file
cat <<EOT >> /home/hadoop/.bashrc
export SCALA_HOME=/usr/local/scala/scala-2.11.7
export PATH=\$PATH:\$SCALA_HOME/bin
EOT


## Reboot manually
