#!/bin/bash
# DO NOT execute this file as super-user
# Script to install hadoop-2.7.1 on ubuntu 14.04 64-bit PC after installing jdk-1.8.0_60
# Step 2- Installing hadoop-2.7.1 (Pseudo-Distributed Mode - Single Node)

# Prerequisites:
# --> Install ubuntu-14.04 (64-bit) on a PC (preferably 4GB RAM) and sufficient free space
# --> Copy the Backup folder on the Desktop (It contains all main tar files for jdk, ant, maven, hipi etc)
#     If the path is changes then make necessary changes in the script as well
# --> Run step1_installJDK before running this file
# --> Make sure you are connected to Internet.
 
# Step 2: hadoop-2.7.1
# To install ssh and rsync
sudo apt-get install ssh rsync

# setup key for ssh so that it does not ask for login pwd # For multi-node setup RSA
## ssh-keygen -t dsa -P "" -f ~/.ssh/id_dsa
## cat ~/.ssh/id_dsa.pub >> ~/.ssh/authorized_keys
ssh-keygen -t rsa -P "" -f ~/.ssh/id_rsa
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

# Extract the hadoop
tar -zxvf ~/Desktop/Backup/hadoop-2.7.1.tar.gz -C ~/

# Export HADOOP_PREFIX
export HADOOP_PREFIX=/home/hadoop/hadoop-2.7.1

# Create the following directories
mkdir -p ~/hadoop_tmp/hdfs/namenode
mkdir -p ~/hadoop_tmp/hdfs/datanode

# Update .bashrc file
cat <<EOT >> ~/.bashrc
export HADOOP_HOME=/home/hadoop/hadoop-2.7.1
export PATH=\$PATH:\$HADOOP_HOME/bin
export PATH=\$PATH:\$HADOOP_HOME/sbin
export HADOOP_MAPRED_HOME=\$HADOOP_HOME
export HADOOP_COMMON_HOME=\$HADOOP_HOME
export HADOOP_HDFS_HOME=\$HADOOP_HOME
export YARN_HOME=\$HADOOP_HOME
export HADOOP_COMMON_LIB_NATIVE_DIR=\$HADOOP_HOME/lib/native
export HADOOP_OPTS="-Djava.library.path=\$HADOOP_HOME/lib"
EOT

# Set JAVA_HOME environment variable in hadoop-env.sh inside HADOOP_HOME/etc/hadoop
sed -i '/export JAVA_HOME=/c\export JAVA_HOME=/usr/local/java/jdk1.8.0_60' ~/hadoop-2.7.1/etc/hadoop/hadoop-env.sh

# Edit ...2.7.1/etc/hadoop/core-site.xml
sed -i '/<configuration>/r core.txt' ~/hadoop-2.7.1/etc/hadoop/core-site.xml

# Edit hdfs-site.xml
sed -i '/<configuration>/r hdfs.txt' ~/hadoop-2.7.1/etc/hadoop/hdfs-site.xml

# Edit yarn-site.xml
sed -i '/<configuration>/r yarn.txt' ~/hadoop-2.7.1/etc/hadoop/yarn-site.xml

# Make a copy of mapred-site.xml.template and rename it to mapred-site.xml
cp ~/hadoop-2.7.1/etc/hadoop/mapred-site.xml.template ~/hadoop-2.7.1/etc/hadoop/mapred-site.xml

# Edit mapred-site.xml
sed -i '/<configuration>/r mapred.txt' ~/hadoop-2.7.1/etc/hadoop/mapred-site.xml

# reboot manually
# To format the namenode
# hdfs namenode -format

# To start dfs
# start-dfs.sh

# To start yarn
# start-yarn.sh

# OR Alternative to the above 2 commands
# start-all.sh

# To check which services are running
# jps

# For Resource Manager webpage
# localhost:8088
# For Namenode webpage
# localhost:50070
